
include("TypeDef.jl")
include("initializations.jl")
include("convolve.jl")
include("padding.jl")
include("pooling.jl")
include("layerForProp.jl")
include("layerBackProp.jl")
include("layerUpdateParams.jl")
include("chain.jl")
include("img2vec.jl")
include("unroll.jl")
