
include("TypeDef.jl")
include("lossFuns.jl")
include("actFuns.jl")
include("initializations.jl")
include("cnn/includes.jl")
include("backForProp.jl")
include("parallelBackForProp.jl")
include("assistance.jl")
include("chain.jl")
